#ifndef ANIMATION_RESOURCE_H
#define ANIMATION_RESOURCE_H

typedef enum ANIMATION_TYPE
{
	ANIM_NONE,
	ANIM_STAND,
	ANIM_MOVE_LEFT,
	ANIM_MOVE_RIGHT,
	ANIM_MOVE_UP,
	ANIM_MOVE_DOWN,
	ANIM_MOVE_LEFT_UP,
	ANIM_MOVE_LEFT_DOWN,
	ANIM_MOVE_RIGHT_UP,
	ANIM_MOVE_RIGHT_DOWN,
} E_ANIMATION_TYPE;

#endif